### ISSUE TITLE
Rewrite external SameAs to allow only authorized domains

### ISSUE THREAD

**Issue by glassjoseph** [snac-cooperative/snac#247]
References Issue #101

Currently, External CPF (SameAs) Relations are entered by pasting the full url to the external entity, and are stored as full urls on the backend in the `otherid` table. 

![image](https://user-images.githubusercontent.com/17987273/79269092-e19c3c80-7e69-11ea-967d-60d3618f2d48.png)

We would like to instead store the authorized domains in one table, and the IDs in another. On the editing interface, we need a dropdown where the editor can select a domain from a list of authorized domains (e.g. Wikidata), and then enter the entity ID from the external record (e.g. Q2157603)  in another input box. The domain and id would then be put together to produce the full url (https://www.wikidata.org/entity/Q2157603) when needed.

This will make the sameAs links easier to update if the base domains change, and easier to limit editors to use only approved sources as External SameAs links.

**Comment by rderik** [comment]
I believe this issue is related to issue https://github.com/snac-cooperative/snac/issues/256, which requests the implementation of the control list using regular expressions. That issue was closed by pull request https://github.com/snac-cooperative/snac/pull/259 when the implementation was completed.

I'll close this issue but feel free to reopen it if something is still pending.
